# Generated by Django 2.2.9 on 2020-07-10 13:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtools.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='page',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='google_ad_code',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='my_stream',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(blank=True, classname='full title', icon='title', max_length=200, template='streams/title_block.html')), ('videoembed', wagtail.embeds.blocks.EmbedBlock('Video embed (YouTube and Facebook)', blank=True, icon='media', label='Enter Video URL', max_length=500, null=True, template='streams/video_embed_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock('Choose an image ...', icon='image', label='Choose an image ...', template='streams/image_block.html')), ('googlemap', wagtail.core.blocks.CharBlock('Google Calendar URL', blank=True, icon='site', label='Enter Google Map URL', max_length=500, null=True, template='streams/google_map_block.html')), ('googlecal', wagtail.core.blocks.CharBlock('Google Calendar URL', blank=True, icon='date', label='Enter Google Calendar URL', max_length=500, null=True, template='streams/google_cal_block.html')), ('code', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.TextBlock()), ('paragraph', wagtail.core.blocks.TextBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('hero', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('classesHeading', wagtail.core.blocks.CharBlock(blank=True, label='Heading CSS (text-dark etc)', required=False)), ('text', wagtail.core.blocks.TextBlock(blank=True, required=False)), ('classesText', wagtail.core.blocks.CharBlock(blank=True, label='CSS classes for Text (text-success etc)', required=False)), ('classes', wagtail.core.blocks.CharBlock(blank=True, label='CSS classes from BS (bg-light or bg-dark)', required=False)), ('background', wagtail.images.blocks.ImageChooserBlock(blank=True, required=False)), ('buttonLabel', wagtail.core.blocks.CharBlock(blank=True, label='Text on button', required=False)), ('buttonUrl', wagtail.core.blocks.URLBlock(blank=True, required=False))])), ('richtext', wagtools.blocks.RichTextBlock()), ('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If nothing selected above.', required=False))])), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title ...', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtools.blocks.CardBlock))])), ('carousel', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtools.blocks.SlideBlock))])), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(blank=True)), ('classes', wagtail.core.blocks.CharBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL', required=False)), ('pagelink', wagtail.core.blocks.PageChooserBlock(blank=True, label='internal URL', required=False))])), ('buttongroup', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title ...', required=False)), ('buttons', wagtail.core.blocks.ListBlock(wagtools.blocks.ButtonBlock))])), ('testimonial', wagtail.core.blocks.StructBlock([('test_name', wagtail.core.blocks.TextBlock(blank=True)), ('test_quote', wagtail.core.blocks.TextBlock(blank=True)), ('test_pic', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('test_reversed', wagtail.core.blocks.BooleanBlock(default=False, required=False))])), ('columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Right column content'))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
